### ISSUE TITLE
No get_var_itemsize in bmilib.h

### ISSUE THREAD

**Issue by goord** [csdms/bmi-c#1]
I am guessing that this function is part of the standard, so I expect to find a function 
```
int BMI_Get_var_itemsize(BMI_model*, const char* name, int* dest);
```
in the bmilib.h file.

**Comment by mdpiper** [comment]
@goord: Hi! I'm half the software engineering team (along with @mcflugen) at CSDMS. We're thrilled that you're using BMI in your work. If you have any questions, or if there's any way we can help, please let us know. Let's keep in touch. You can reach me at mark.piper@colorado.edu.

**Comment by goord** [comment]
Hi @mdpiper, thanks, we will keep you updated regarding our experiences with BMI. If you're curious, I am working on https://github.com/eWaterCycle/grpc4bmi, a package to combine BMI with (docker) containers via remote protocol buffers.
